# Generated by Django 2.1.5 on 2019-04-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_ingredients_ingredient_convert'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_instructions',
            field=models.TextField(default=' ', max_length=1000),
            preserve_default=False,
        ),
    ]
